export enum RegisterAction {
    AGREE_TERMS = "AGREE_TERMS",
    DISAGREE_TERMS = "DISAGREE_TERMS",
    AGREE_USERNAME_PERMISSION = "AGREE_USERNAME_PERMISSION",
    DISAGREE_USERNAME_PERMISSION = "DISAGREE_USERNAME_PERMISSION",
    USERNAME_PERMISSION = "USERNAME_PERMISSION",
}
